---
- name: Ensure Java is installed
  yum:
    name: java-11-openjdk
    state: present

- name: Add Jenkins repository key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    enabled: yes

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled
  systemd:
    name: jenkins
    state: started
    enabled: yes
