---
- name: Install Ruby and Bundler
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby
    - rubygems

- name: Create Gemfile for Serverspec
  copy:
    dest: /root/Gemfile
    content: |
      source 'https://rubygems.org'
      gem 'serverspec'
      gem 'coderay'  # 추가: HTML 출력을 위한 코드레이 gem 추가

- name: Install gems using bundler
  command: /usr/bin/bundle install --path vendor/bundle
  args:
    chdir: /root

- name: Create /usr/test directory
  file:
    path: /usr/test
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy nginx_spec.rb file
  copy:
    src: ../spec/nginx_spec.rb # 로컬 PC에 위치한 nginx_spec.rb 파일 경로
    dest: /root/nginx_spec.rb

- name: Run Serverspec tests and generate HTML report
  command: /usr/bin/bundle exec rspec --format html --out /root/serverspec_report.html /root/nginx_spec.rb
  args:
    chdir: /root
  register: result

- name: Display Serverspec test results
  debug:
    var: result.stdout

- name: Transfer HTML report to local machine
  fetch:
    src: /root/serverspec_report.html
    dest: /test
    flat: yes
