---
- name: Install Ruby and Bundler
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - ruby
    - rubygems
    - ruby-devel
    - gcc
    - make

- name: Create Gemfile for Serverspec
  copy:
    dest: /root/Gemfile
    content: |
      source 'https://rubygems.org'
      gem 'serverspec'
      gem 'coderay'

- name: Set bundle path configuration
  command: bundle config set path 'vendor/bundle'
  args:
    chdir: /root

- name: Install gems using bundler
  command: bundle install
  args:
    chdir: /root
  become: yes
  become_user: root

- name: Create /usr/test directory
  file:
    path: /usr/test
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy nginx_spec.rb file
  copy:
    src: ../spec/nginx_spec.rb
    dest: /root/nginx_spec.rb

- name: Run Serverspec tests and generate HTML report
  command: bundle exec rspec --format html --out /root/serverspec_report.html /root/nginx_spec.rb
  args:
    chdir: /root
  register: result
  become: yes
  become_user: root

- name: Display Serverspec test results
  debug:
    var: result.stdout

- name: Check if Serverspec report exists
  stat:
    path: /root/serverspec_report.html
  register: st

- name: Fail if Serverspec report is not found
  fail:
    msg: "oops! file not found"
  when: not st.stat.exists

- name: Transfer HTML report to local machine
  copy:
    remote_src: yes
    src: /root/serverspec_report.html
    dest: /test/serverspec_report.html
