---
- name: Ensure Python3 is installed
  hosts: webservers
  become: yes
  tasks:
    - name: Install Python3
      yum:
        name: python3
        state: present

- name: Configure firewalld
  hosts: webservers
  become: yes
  tasks:
    - name: Add HTTP service to firewalld
      firewalld:
        service: http
        state: enabled
        immediate: yes

    - name: Add HTTPS service to firewalld
      firewalld:
        service: https
        state: enabled
        immediate: yes

- name: Essential file installation
  hosts: webservers
  become: yes
  tasks:
    - name: Install essential packages
      yum:
        name:
          - vim
          - git
          - curl
        state: present

- name: Ensure /test directory exists and has correct permissions
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure /test directory exists
      file:
        path: /test
        state: directory
        mode: "0755"
        owner: root
        group: root

- name: Provision and test infrastructure
  hosts: webservers
  become: yes
  roles:
    - nginx
    - serverspec
    - jenkins
