---
- name: Deploy Web Server
  hosts: rocky  # 호스트 설정 - 웹 서버를 띄울 서버의 호스트명 또는 IP 주소를 입력합니다.

  tasks:
    - name: Install Apache Web Server
      become: yes  # root 권한으로 실행
      dnf:
        name: httpd  # Rocky Linux 기준 패키지 이름
        state: present  # 설치 상태 확인 및 설치

    - name: Create index.html
      become: yes
      template:
        src: templates/index.html.j2  # index.html.j2 템플릿 파일 경로
        dest: /var/www/html/index.html  # 생성될 index.html 파일 경로
      notify: Restart Apache  # 템플릿이 변경되면 Apache를 재시작하도록 알림

  handlers:
    - name: Restart Apache
      become: yes
      systemd:
        name: httpd
        state: restarted  # Apache 재시작

